// Generated by tools/generate_game_content.mjs. Edit content/ sources instead.
const content = {
  "version": 2,
  "levelCount": 40,
  "qiCap": 100,
  "expRates": [
    30,
    60,
    80,
    100
  ],
  "tiles": [
    {
      "id": 0,
      "name": "Kiếm",
      "damage": 10,
      "qi": 1
    },
    {
      "id": 1,
      "name": "Hỏa",
      "damage": 6,
      "qi": 2
    },
    {
      "id": 2,
      "name": "Lôi",
      "damage": 4,
      "qi": 3
    },
    {
      "id": 3,
      "name": "Tụ Linh Châu",
      "damage": 0,
      "qi": 6
    }
  ],
  "realms": [
    {
      "id": "LuyenKhi",
      "name": "Luyện Khí",
      "exp": 0
    },
    {
      "id": "TrucCo",
      "name": "Trúc Cơ",
      "exp": 1500
    },
    {
      "id": "KimDan",
      "name": "Kim Đan",
      "exp": 4000
    },
    {
      "id": "NguyenAnh",
      "name": "Nguyên Anh",
      "exp": 8000
    },
    {
      "id": "HoaThan",
      "name": "Hóa Thần",
      "exp": 14000
    },
    {
      "id": "LuyenHu",
      "name": "Luyện Hư",
      "exp": 23000
    },
    {
      "id": "HopThe",
      "name": "Hợp Thể",
      "exp": 36000
    },
    {
      "id": "DaiThua",
      "name": "Đại Thừa",
      "exp": 54000
    },
    {
      "id": "DoKiep",
      "name": "Độ Kiếp",
      "exp": 78000
    },
    {
      "id": "ChanTien",
      "name": "Chân Tiên",
      "exp": 110000
    }
  ],
  "skills": [
    {
      "id": "nhat-kiem",
      "name": "Nhất Kiếm",
      "description": "Chém một hàng ngang được chọn.",
      "cost": 60,
      "unlock": 0,
      "price": 0,
      "target": "row",
      "icon": "剑"
    },
    {
      "id": "ngu-kiem",
      "name": "Ngự Kiếm",
      "description": "Đổi hai ô cạnh nhau, ít nhất một ô Kiếm. Không cần tạo match.",
      "cost": 30,
      "unlock": 3,
      "price": 150,
      "target": "pair",
      "icon": "↔"
    },
    {
      "id": "hoa-lien",
      "name": "Hỏa Liên",
      "description": "Nổ vùng 3×3 quanh ô chọn.",
      "cost": 65,
      "unlock": 5,
      "price": 200,
      "target": "cell",
      "icon": "火"
    },
    {
      "id": "dan-loi",
      "name": "Dẫn Lôi",
      "description": "Chọn ba ô thường khác Lôi để chuyển thành Lôi.",
      "cost": 45,
      "unlock": 8,
      "price": 250,
      "target": "triple",
      "icon": "ϟ"
    },
    {
      "id": "pha-chuong",
      "name": "Phá Chướng",
      "description": "Gỡ đá và phong ấn trong vùng 3×3.",
      "cost": 40,
      "unlock": 12,
      "price": 300,
      "target": "cell",
      "icon": "破"
    },
    {
      "id": "lien-kiem",
      "name": "Liên Kiếm",
      "description": "Chọn hai ô cường hóa để kích hoạt lần lượt.",
      "cost": 80,
      "unlock": 15,
      "price": 350,
      "target": "chargedPair",
      "icon": "双"
    },
    {
      "id": "hoi-linh",
      "name": "Hồi Linh",
      "description": "Xáo các ô di chuyển được trong vùng 3×3.",
      "cost": 35,
      "unlock": 20,
      "price": 450,
      "target": "cell",
      "icon": "↻"
    },
    {
      "id": "van-kiem",
      "name": "Vạn Kiếm",
      "description": "Chọn một ô để xóa toàn bộ ô cùng loại.",
      "cost": 100,
      "unlock": 30,
      "price": 500,
      "target": "kind",
      "icon": "万"
    }
  ],
  "swords": [
    {
      "id": "thanh-phong",
      "name": "Thanh Phong",
      "description": "Ô Kiếm nhận thêm 1 kiếm khí.",
      "unlock": 0,
      "price": 0,
      "color": "#49c8e5"
    },
    {
      "id": "trong-nhac",
      "name": "Trọng Nhạc",
      "description": "Sát thương ô Kiếm tăng 30%.",
      "unlock": 3,
      "price": 200,
      "color": "#d7b76e"
    },
    {
      "id": "hoa-van",
      "name": "Hỏa Vân",
      "description": "Sát thương ô Hỏa tăng 50%.",
      "unlock": 5,
      "price": 200,
      "color": "#e35646"
    },
    {
      "id": "loi-minh",
      "name": "Lôi Minh",
      "description": "Ô Lôi nhận thêm 1 kiếm khí.",
      "unlock": 8,
      "price": 250,
      "color": "#b79aff"
    },
    {
      "id": "tu-linh",
      "name": "Tụ Linh",
      "description": "Khí cơ bản của Tụ Linh Châu tăng thêm 2.",
      "unlock": 12,
      "price": 300,
      "color": "#7ce4bd"
    },
    {
      "id": "lien-tinh",
      "name": "Liên Tinh",
      "description": "Sát thương tăng 20% từ cascade thứ hai.",
      "unlock": 15,
      "price": 350,
      "color": "#f2d58e"
    },
    {
      "id": "pha-quan",
      "name": "Phá Quân",
      "description": "Ô bị xóa phá chướng ngại cạnh bên theo tám hướng.",
      "unlock": 20,
      "price": 400,
      "color": "#efac82"
    },
    {
      "id": "huyen-co",
      "name": "Huyền Cơ",
      "description": "Giảm 10% chi phí kiếm thuật.",
      "unlock": 30,
      "price": 450,
      "color": "#87c3dc"
    }
  ],
  "levelBands": [
    {
      "chapter": "Vân Hải Tiên Sơn",
      "moves": 24,
      "collect": 18,
      "seals": 4,
      "rocks": 3,
      "battle": 220,
      "boss": 360
    },
    {
      "chapter": "Huyền Kiếm Bí Cảnh",
      "moves": 24,
      "collect": 24,
      "seals": 6,
      "rocks": 4,
      "battle": 320,
      "boss": 520
    },
    {
      "chapter": "Lôi Hỏa Thiên Môn",
      "moves": 22,
      "collect": 30,
      "seals": 8,
      "rocks": 5,
      "battle": 420,
      "boss": 680
    },
    {
      "chapter": "Tinh Hà Kiếm Vực",
      "moves": 22,
      "collect": 36,
      "seals": 10,
      "rocks": 6,
      "battle": 520,
      "boss": 840
    }
  ]
} as const;
export const CONTENT = content;
export const LEVEL_COUNT = content.levelCount;
export const SKILLS = content.skills;
export const SWORDS = content.swords;
export const REALMS = content.realms;
export type SkillId = typeof SKILLS[number]['id'];
export type SwordId = typeof SWORDS[number]['id'];
export type Stars = 0 | 1 | 2 | 3;
export interface LevelResult {
    levelId: number;
    stars: Stars;
}
export interface Loadout {
    skills: SkillId[];
    sword: SwordId;
}
export interface PlayerProfile {
    levels: LevelResult[];
    coins: number;
    ownedSkills: SkillId[];
    ownedSwords: SwordId[];
    loadout: Loadout;
    revision: number;
    totalExp: number;
}
export type PlayerOperation = {
    id: string;
    kind: 'win';
    levelId: number;
    stars: Stars;
} | {
    id: string;
    kind: 'purchase';
    category: 'skill' | 'sword';
    itemId: string;
} | {
    id: string;
    kind: 'equip';
    loadout: Loadout;
} | {
    id: string;
    kind: 'importProgress';
    levels: LevelResult[];
};
export interface OperationReward {
    id: string;
    expGained: number;
    coinsGained: number;
    bestStars: Stars;
    realmBefore: number;
    realmAfter: number;
}
export interface SyncResponse {
    profile: PlayerProfile;
    acknowledged: string[];
    rewards?: OperationReward[];
    rejected: {
        id: string;
        reason: string;
    }[];
}
export function emptyProfile(): PlayerProfile {
    return { levels: [], coins: 0, ownedSkills: ['nhat-kiem'], ownedSwords: ['thanh-phong'], loadout: { skills: ['nhat-kiem'], sword: 'thanh-phong' }, revision: 0, totalExp: 0 };
}
export function normalizeLevels(raw: unknown): LevelResult[] {
    if (!Array.isArray(raw))
        return [];
    const map = new Map<number, Stars>();
    for (const item of raw) {
        if (!item || !Number.isInteger(item.levelId) || item.levelId < 1 || item.levelId > LEVEL_COUNT || !Number.isInteger(item.stars) || item.stars < 0 || item.stars > 3)
            continue;
        map.set(item.levelId, Math.max(map.get(item.levelId) ?? 0, item.stars) as Stars);
    }
    const result: LevelResult[] = [];
    for (let id = 1; id <= LEVEL_COUNT && map.has(id); id++)
        result.push({ levelId: id, stars: map.get(id)! });
    return result;
}
export function mergeLevels(a: LevelResult[], b: LevelResult[]): LevelResult[] { return normalizeLevels([...a, ...b]); }
export function totalExp(levels: LevelResult[]): number { return normalizeLevels(levels).reduce((sum, level) => sum + expForStars(level.stars, getLevelData(level.levelId).baseExp), 0); }
export function expForStars(stars: Stars, baseExp = 100): number { return Math.floor(baseExp * content.expRates[stars] / 100); }
export function highestUnlocked(levels: LevelResult[]): number { return Math.min(LEVEL_COUNT, normalizeLevels(levels).length + 1); }
export function isCompleted(levels: LevelResult[], id: number): boolean { return levels.some(x => x.levelId === id); }
export function gradeStars(moves: number, initialMoves: number): Stars { return moves >= initialMoves * .25 ? 3 : moves >= initialMoves * .1 ? 2 : moves > 0 ? 1 : 0; }
export function starBonus(stars: Stars): number { return Math.max(0, stars - 1) * 25; }
export function realmForExp(exp: number) {
    const safe = Math.max(0, Math.floor(exp));
    let index = 0;
    while (index + 1 < REALMS.length && safe >= REALMS[index + 1].exp)
        index++;
    const realm = REALMS[index];
    const next = REALMS[index + 1];
    const progress = next ? Math.min(1, (safe - realm.exp) / (next.exp - realm.exp)) : 1;
    const stage = next ? Math.min(3, Math.floor(progress * 4)) : 0;
    return { ...realm, index, next, progress, stage, stageName: next ? ['Sơ kỳ', 'Trung kỳ', 'Hậu kỳ', 'Viên mãn'][stage] : 'Chân Tiên', damageScale: 1.25 ** index * (1 + .05 * stage), skillSlots: safe >= 1500 ? 2 : 1 };
}
export function getLevelData(id: number) {
    if (!Number.isInteger(id) || id < 1 || id > LEVEL_COUNT)
        throw new Error('INVALID_LEVEL');
    const bandIndex = Math.floor((id - 1) / 10);
    const band = content.levelBands[bandIndex];
    const step = (id - 1) % 10;
    const goal = id === 15 || step === 9 ? 'Boss' : step < 4 ? 'Collect' : step === 5 ? 'BreakSeals' : step === 7 ? 'BreakRocks' : 'Battle';
    return { id, chapter: band.chapter, moves: band.moves, goal, collectKind: step < 4 ? step : 0, target: goal === 'Collect' ? band.collect : goal === 'BreakSeals' ? band.seals : goal === 'BreakRocks' ? band.rocks : goal === 'Boss' ? band.boss : band.battle, rocks: goal === 'BreakRocks' ? band.rocks : goal === 'BreakSeals' ? 0 : bandIndex, seals: goal === 'BreakSeals' ? band.seals : goal === 'BreakRocks' ? 0 : bandIndex, seed: 7919 + id * 104729, baseExp: 100 };
}
export function skillCost(id: SkillId, sword: SwordId, condensed: boolean): number {
    const skill = SKILLS.find(x => x.id === id);
    if (!skill)
        throw new Error('INVALID_SKILL');
    return Math.max(1, Math.ceil(skill.cost * (sword === 'huyen-co' ? .9 : 1) * (condensed ? .75 : 1)));
}
export function validLoadout(raw: unknown, profile: PlayerProfile): Loadout | null {
    if (!raw || typeof raw !== 'object')
        return null;
    const loadout = raw as Loadout;
    if (!Array.isArray(loadout.skills) || loadout.skills.length < 1 || loadout.skills.length > realmForExp(totalExp(profile.levels)).skillSlots || new Set(loadout.skills).size !== loadout.skills.length || !loadout.skills.every(id => profile.ownedSkills.includes(id)) || !profile.ownedSwords.includes(loadout.sword))
        return null;
    return { skills: [...loadout.skills], sword: loadout.sword };
}
export function normalizeProfile(raw: unknown): PlayerProfile | null {
    if (!raw || typeof raw !== 'object')
        return null;
    const p = raw as PlayerProfile;
    if (!Array.isArray(p.levels) || !Number.isSafeInteger(p.coins) || p.coins < 0 || !Array.isArray(p.ownedSkills) || !Array.isArray(p.ownedSwords))
        return null;
    const result: PlayerProfile = { ...emptyProfile(), levels: normalizeLevels(p.levels), coins: p.coins, ownedSkills: [...new Set<SkillId>(['nhat-kiem', ...p.ownedSkills.filter(id => SKILLS.some(x => x.id === id))])], ownedSwords: [...new Set<SwordId>(['thanh-phong', ...p.ownedSwords.filter(id => SWORDS.some(x => x.id === id))])], revision: Number.isSafeInteger(p.revision) && p.revision >= 0 ? p.revision : 0, totalExp: 0 };
    result.totalExp = totalExp(result.levels);
    result.loadout = validLoadout(p.loadout, result) ?? result.loadout;
    return result;
}
export function profileFromLegacy(levels: LevelResult[]): PlayerProfile {
    const normalized = normalizeLevels(levels);
    return { ...emptyProfile(), levels: normalized, coins: normalized.reduce((sum, x) => sum + 100 + starBonus(x.stars), 0), totalExp: totalExp(normalized) };
}
export function parseOperation(raw: unknown): PlayerOperation | null {
    if (!raw || typeof raw !== 'object')
        return null;
    const op = raw as PlayerOperation;
    if (typeof op.id !== 'string' || !/^[a-zA-Z0-9_-]{8,120}$/.test(op.id))
        return null;
    if (op.kind === 'win' && Number.isInteger(op.levelId) && op.levelId >= 1 && op.levelId <= LEVEL_COUNT && Number.isInteger(op.stars) && op.stars >= 0 && op.stars <= 3)
        return { id: op.id, kind: op.kind, levelId: op.levelId, stars: op.stars };
    if (op.kind === 'purchase' && (op.category === 'skill' || op.category === 'sword') && typeof op.itemId === 'string')
        return { id: op.id, kind: op.kind, category: op.category, itemId: op.itemId };
    if (op.kind === 'equip' && op.loadout && Array.isArray(op.loadout.skills) && op.loadout.skills.every(x => typeof x === 'string') && typeof op.loadout.sword === 'string')
        return { id: op.id, kind: op.kind, loadout: { skills: [...op.loadout.skills], sword: op.loadout.sword } };
    if (op.kind === 'importProgress' && Array.isArray(op.levels) && op.levels.length <= LEVEL_COUNT && op.levels.every(x => x && Number.isInteger(x.levelId) && x.levelId >= 1 && x.levelId <= LEVEL_COUNT && Number.isInteger(x.stars) && x.stars >= 0 && x.stars <= 3) && normalizeLevels(op.levels).length === op.levels.length)
        return { id: op.id, kind: op.kind, levels: normalizeLevels(op.levels) };
    return null;
}
export function applyOperation(profile: PlayerProfile, op: PlayerOperation): {
    profile: PlayerProfile;
    error?: string;
} {
    const p: PlayerProfile = { ...profile, levels: [...profile.levels], ownedSkills: [...profile.ownedSkills], ownedSwords: [...profile.ownedSwords], loadout: { ...profile.loadout, skills: [...profile.loadout.skills] } };
    if (op.kind === 'win') {
        if (op.levelId > highestUnlocked(p.levels))
            return { profile, error: 'LEVEL_LOCKED' };
        const previous = p.levels.find(x => x.levelId === op.levelId);
        p.coins += previous ? 10 + Math.max(0, starBonus(op.stars) - starBonus(previous.stars)) : 100 + starBonus(op.stars);
        p.levels = mergeLevels(p.levels, [{ levelId: op.levelId, stars: op.stars }]);
    }
    else if (op.kind === 'importProgress') {
        const merged = mergeLevels(p.levels, op.levels);
        for (const level of merged) {
            const old = p.levels.find(x => x.levelId === level.levelId);
            p.coins += old ? Math.max(0, starBonus(level.stars) - starBonus(old.stars)) : 100 + starBonus(level.stars);
        }
        p.levels = merged;
    }
    else if (op.kind === 'purchase') {
        const item = (op.category === 'skill' ? SKILLS : SWORDS).find(x => x.id === op.itemId);
        if (!item)
            return { profile, error: 'INVALID_ITEM' };
        const owned: string[] = op.category === 'skill' ? p.ownedSkills : p.ownedSwords;
        if (owned.includes(item.id))
            return { profile, error: 'ALREADY_OWNED' };
        if (p.levels.length < item.unlock)
            return { profile, error: 'ITEM_LOCKED' };
        if (p.coins < item.price)
            return { profile, error: 'INSUFFICIENT_COINS' };
        p.coins -= item.price;
        if (op.category === 'skill')
            p.ownedSkills.push(item.id as SkillId);
        else
            p.ownedSwords.push(item.id as SwordId);
    }
    else {
        const loadout = validLoadout(op.loadout, p);
        if (!loadout)
            return { profile, error: 'INVALID_LOADOUT' };
        p.loadout = loadout;
    }
    p.totalExp = totalExp(p.levels);
    p.revision++;
    return { profile: p };
}
export function mergeProfiles(a: PlayerProfile, b: PlayerProfile): PlayerProfile {
    const result = { ...b, levels: mergeLevels(a.levels, b.levels), coins: a.coins + b.coins, ownedSkills: [...new Set([...a.ownedSkills, ...b.ownedSkills])], ownedSwords: [...new Set([...a.ownedSwords, ...b.ownedSwords])], revision: Math.max(a.revision, b.revision) + 1 };
    result.totalExp = totalExp(result.levels);
    result.loadout = validLoadout(b.loadout, result) ?? emptyProfile().loadout;
    return result;
}
