import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const template=fs.readFileSync(path.join(root,'content/game-domain.ts'),'utf8');
// Share schemas and pure rules, never embed the seed catalog in a client build.
const generated='// Generated by tools/generate_game_content.mjs. Edit content/game-domain.ts instead.\n'+template;
for(const target of ['client/src/game/domain.ts','server/src/domain/game.ts']) {
 const destination=path.join(root,target);
 if(process.argv.includes('--check')) {if(!fs.existsSync(destination)||fs.readFileSync(destination,'utf8')!==generated)throw new Error(`Stale domain: ${target}`);}
 else fs.writeFileSync(destination,generated);
}
