import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const content = JSON.parse(fs.readFileSync(path.join(root, 'content/game-content.json'), 'utf8'));
if (content.version !== 2 || content.levelCount !== 40 || content.tiles.length !== 4 || content.skills.length !== 8 || content.swords.length !== 8 || content.realms.length !== 10) throw new Error('Invalid content catalog');
for (const list of [content.skills, content.swords, content.realms]) {
  if (new Set(list.map(x => x.id)).size !== list.length) throw new Error('Duplicate content ID');
}
if (content.tiles[3].damage !== 0 || content.realms.at(-1).id !== 'ChanTien') throw new Error('Invalid progression rules');
const template = fs.readFileSync(path.join(root, 'content/game-domain.ts'), 'utf8');
const generated = '// Generated by tools/generate_game_content.mjs. Edit content/ sources instead.\n' + template.replace("import content from './game-content.json';", `const content = ${JSON.stringify(content, null, 2)} as const;`);
for (const target of ['client/src/game/domain.ts', 'server/src/domain/game.ts']) {
  const destination = path.join(root, target);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8') !== generated) throw new Error(`Stale generated content: ${target}`);
  } else {
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, generated);
  }
}
